/* autogenerated by Processing revision 1292 on 2023-05-10 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;
import java.util.Map;

public class Processing extends PApplet{
  private PImage startmenu;
public void setup(){
  /* size commented out by preprocessor */;
  frameRate(30);
  textSize(65);
  this.startmenu = loadImage("images/space.jpg");
}

private void startMenu(){
  background(this.startmenu);
  textAlign(CENTER);
  text("Welcome to SpaceWars",width/2.0f,60);

}

public void draw(){
  startMenu();
}

  public void settings() {
    size(800, 800);
  }

  public void keyPressed(){
    switch (this.key){
      case('a'):
        //new Communicator();
        break;

      case('w'):
        break;

      case('d'):
        break;

    }
  }

  public static void main(String[] args) {
    //if(args.length < 2)
    //    System.exit(1);

    //String host = args[0];
    //int port = Integer.parseInt(args[1]);

    try{
      //Socket socket = new Socket(host, port);
      //ConnectionManager cm = ConnectionManager.start(socket);

      String[] processingArgs = {"Processing"};
      PApplet.runSketch(processingArgs, new Processing());
    } catch(Exception e){
      e.printStackTrace();
      System.exit(0);
    }
  }
}
